name: 'send-slack-notification'
description: 'Publish customized message in a Slack channel'
inputs:
  channel-id:
    description: 'Slack channel ID or channel name where message will be posted.'
    required: true
  title:
    description: "Title text for the message"
    required: true
  attachment_color:
    description: 'Attachment color'
    required: false
  aws_role:
    description: "The AWS role to assume"
    required: true   

runs:
  using: 'composite'
  steps:
   - id: configure_aws_cred
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: us-west-2

    - id: get_bot_token_from_aws
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          BOT_TOKEN_SLACK, dxp/slack/app/bot/token

    - id: slack_bot_token_value
      shell: bash
      run: |
        BOT_TOKEN_SLACK=$(echo ${{ env.BOT_TOKEN_SLACK }} | tr -d '{}' | cut -c 25-)
        echo "SLACK_TOKEN_SHORT=${BOT_TOKEN_SLACK}" >> $GITHUB_OUTPUT
    - id: generate_payload
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        TITLE_TEXT: ${{ inputs.title }}
        ATTACHMENT_COLOR: ${{ inputs.attachment_color }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_PULL_REQUEST_BRANCH: ${{ github.head_ref }}
        GITHUB_TRIGGER_BRANCH: ${{ github.ref }}
        WORKFLOW_RUN_ID: ${{ github.run_id }}
        SLACK_GITHUB_AUTHOR: ${{ github.actor }}
      run: |
        python3 payload_generation.py

    - id: send_slack_message
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload-file-path: "${{ github.action_path }}/payload.json"
        channel-id: ${{ inputs.channel-id }}
      env:
        SLACK_BOT_TOKEN: ${{ steps.slack_bot_token_value.outputs.SLACK_TOKEN_SHORT }}

