name: "Test Terraform"
description: "Install Terraform and use it to test the current template"
inputs:
  version:
    description: "The terraform version to test"
    required: true


runs:
  using: 'composite'
  steps:

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.version }}

    - name: Test Terraform
      run: |
        "${{ github.action_path }}/ci_tests.sh ${{ github.repository }}