on:
  workflow_call:
    secrets:
      aws_role:
        required: true
      lw_account:
        required: true
      lw_api_key:
        required: true
      lw_api_secret:
        required: true
      lw_subaccount:
        required: true

jobs:
  run-tests:
    strategy:
      matrix:
        version: [1.0.0, 1.4, 1.5]    
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role }}
          aws-region: us-west-2

      - name: Install Lacework CLI
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash
          lacework version

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.version }}
          terraform_wrapper: false

      - name: Test Terraform
        shell: bash
        run: |
          terraform version
          ./scripts/ci_tests.sh
        env:
          LW_ACCOUNT: ${{ secrets.lw_account }}
          LW_API_KEY: ${{ secrets.lw_api_key }}
          LW_API_SECRET: ${{ secrets.lw_api_secret }}
          LW_SUBACCOUNT: ${{ secrets.lw_subaccount }}


