on: 
  workflow_call:
    inputs:
      tf-versions:
        type: string
        description: "List of Terraform versions to test"
        default: ["1.0.0", "1.4", "1.5"]
jobs:
  run-tests:
    strategy:
      matrix:
        version: ${{ fromJSON(github.event.inputs.tf-versions) }}  
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::249446771485:role/tf-role-arc-generic
          aws-region: us-west-2

      - name: Install Lacework CLI
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash
          lacework version
          jq -n \
          --arg ac "$LW_ACCOUNT" \
          --arg ke "$LW_API_KEY" \
          --arg se "$LW_API_SECRET" \
          --arg su "$LW_SUBACCOUNT" \
          '{keyId: $ke, secret: $se, subAccount: $su, account: 9$ac + ".lacework.net")}' > creds.json
          lacework configure -j creds.json --noninteractive 
        env:
          LW_ACCOUNT: ${{ secrets.tf_lw_account }}
          LW_API_KEY: ${{ secrets.tf_lw_api_key }}
          LW_API_SECRET: ${{ secrets.tf_lw_api_secret }}
          LW_SUBACCOUNT: ${{ secrets.tf_lw_subaccount }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.version }}
          terraform_wrapper: false

      - name: Install tfsec
        shell: bash
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version

      - name: Test Terraform
        shell: bash
        run: |
          terraform version
          ./scripts/ci_tests.sh



