on: workflow_call

jobs:
  prepare-release:  
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.TF_TOKEN }}


      - name: Prepare release
        shell: bash
        run: |
          echo "$GPG_SECRET_KEY" | base64 --decode | gpg --import --no-tty --batch --yes
          scripts/release.sh prepare
        env:
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GITHUB_TOKEN: ${{ secrets.TF_TOKEN }}




